spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    #    show-sql: true      # (2) SQL 쿼리 출력
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
#        use_sql_comments: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  freemarker:
    cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false

  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${mail.username} # SMTP 서버 로그인 아이디 (발신자)
    password: ${mail.password} # SMTP 서버 로그인 패스워드 (앱 비밀번호)
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부 (기본값 : false)
          timeout: 5000 # Socket Read Timeout 시간(ms) (기본값 : 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값 : false)

secret: cos_jwt_token

logging.level:
  org.hibernate:
    SQL: info
    type: info

